type Beneficiary {
  contact: Contact
  contactId: ID
  dateOfBirth: DateTimeISO
  deceasedRelation: String
  id: ID!
  user: User
  userId: ID
}

type Contact {
  completeAddress: String
  displayName: String
  email: String
  gender: String
  id: ID!
  name: String!
  phone: String
  postalCode: String
  surname: String!
}

input CreateBeneficiaryInput {
  contactId: ID
  dateOfBirth: DateTimeISO
  deceasedRelation: String
  userId: ID
}

input CreateContactInput {
  completeAddress: String
  displayName: String
  email: String
  gender: String
  name: String!
  phone: String
  postalCode: String
  surname: String!
}

input CreateInheritanceProcedureInput {
  deceasedPersonId: ID
  endDate: DateTimeISO!
  name: String!
  notaryId: ID
  startDate: DateTimeISO!
  state: String
}

input CreateNotaryInput {
  contactId: ID
  userId: ID
}

"""
A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.This scalar is serialized to a string in ISO 8601 format and parsed from a string in ISO 8601 format.
"""
scalar DateTimeISO

type DeceasedPerson {
  contactId: ID!
  dateOfBirth: DateTimeISO!
  dateOfDeath: DateTimeISO!
  id: Int!
}

input FindNotaryInput {
  deceasedPersonDateOfDeath: DateTimeISO!
  postalCode: String!
}

type InheritanceProcedure {
  deceasedPerson: DeceasedPerson
  deceasedPersonId: ID
  endDate: String
  id: ID!
  name: String!
  notary: Notary
  notaryId: ID
  startDate: DateTimeISO!
  state: String!
}

type Mutation {
  addBeneficiaryToProcedure(beneficiaryId: Int!, procedureId: Int!): Boolean!
  assignNotary(notaryId: Int!, procedureId: Int!): Boolean!
  changePassword(newPassword: String!, oldPassword: String!): User!
  closeProcedure(procedureId: Int!): Boolean!
  confirmEmailVerification(token: String!): Boolean!
  createBeneficiaries(data: [CreateBeneficiaryInput!]!): [Beneficiary!]!
  createBeneficiary(data: CreateBeneficiaryInput!): Beneficiary!
  createContact(data: CreateContactInput!): Int!
  createNotary(data: CreateNotaryInput!): Notary!
  createProcedure(data: CreateInheritanceProcedureInput!): Int!
  deleteBeneficiary(id: Int!): Boolean!
  deleteContactById(id: Float!): Int!
  deleteNotary(id: Float!): Notary!
  removeBeneficiaryFromProcedure(
    beneficiaryId: Int!
    procedureId: Int!
  ): Boolean!
  requestPasswordReset(email: String!): Boolean!
  resetPassword(newPassword: String!, token: String!): Boolean!
  signIn(login: String!, password: String!): SignInResponse!
  signUp(registerInput: RegisterInput!): User!
  updateBeneficiary(data: UpdateBeneficiaryInput!, id: Int!): Beneficiary!
}

type Notary {
  contact: Contact
  contactId: ID
  id: ID!
  user: User
  userId: ID
}

type Query {
  _empty: String!
  author(id: Float!): Notary
  findNotary(input: FindNotaryInput!): Notary
  getAllContacts: [Contact!]!
  getBeneficiariesByIds(ids: [Int!]!): [Beneficiary!]!
  getBeneficiariesByProcedureId(procedureId: Int!): [Beneficiary!]!
  getBeneficiaryById(id: Int!): Beneficiary
  getContactById(id: Float!): Contact
  getProcedureById(id: Int!): InheritanceProcedure
  getUserById(id: Float!): User
  notaries: [Notary!]!
}

input RegisterInput {
  email: String!
  name: String!
  password: String!
  surname: String!
}

type SignInResponse {
  token: String!
  user: User!
}

input UpdateBeneficiaryInput {
  contactId: ID
  dateOfBirth: DateTimeISO
  deceasedRelation: String
  userId: ID
}

type User {
  beneficiary: Beneficiary
  email: String!
  id: ID!
  notary: Notary
  password: String!
}
