image: node:20.17.0

stages:
  - verify
  - deploy
  - e2e

variables:
  YARN_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/yarn'

.rules:
  rules:
    - if: ($CI_PIPELINE_SOURCE == "merge_request_event")
    - if: ($CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push")

install:
  stage: verify
  interruptible: true
  rules:
    - !reference [.rules, rules]
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - cache/yarn
      - node_modules
    policy: push
  script:
    - yarn install --frozen-lockfile

format:
  stage: verify
  interruptible: true
  rules:
    - !reference [.rules, rules]
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - cache/yarn
      - node_modules
    policy: pull
  script:
    - yarn format:check
  needs:
    - install

lint:
  stage: verify
  interruptible: true
  rules:
    - !reference [.rules, rules]
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - cache/yarn
      - node_modules
    policy: pull
  script:
    - yarn lint
  needs:
    - format

test-frontend:
  stage: verify
  interruptible: true
  rules:
    - !reference [.rules, rules]
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - cache/yarn
      - node_modules
    policy: pull
  script:
    - yarn frontend test
  needs:
    - lint

build-frontend:
  stage: verify
  interruptible: true
  rules:
    - if: ($CI_PIPELINE_SOURCE == "merge_request_event")
    - if: ($CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push")
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - cache/yarn
      - node_modules
    policy: pull
  script:
    - yarn frontend build
  needs:
    - test-frontend

build-backend:
  stage: verify
  interruptible: true
  rules:
    - if: ($CI_PIPELINE_SOURCE == "merge_request_event")
    - if: ($CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push")
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - cache/yarn
      - node_modules
    policy: pull
  script:
    - yarn backend build
  needs:
    - lint

pull-changes:
  stage: deploy
  interruptible: true
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - chmod 400 "$SSH_PRIVATE_KEY"
    - ssh-add "$SSH_PRIVATE_KEY"
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -oStrictHostKeyChecking=no team03@vse.handson.pro "cd code/project && git pull"
  only:
    - main  # This will run only on the 'main' branch

e2e-testing:
  stage: e2e
  image: mcr.microsoft.com/playwright:v1.48.1-noble
  script:
    - echo FRONTEND_URL="$FRONTEND_URL" >> .env
    - echo BACKEND_URL="$BACKEND_URL" >> .env
    - yarn install --frozen-lockfile
    - yarn test:e2e
  only:
    - main
    
