export const route = {
  home: () => `/`,
  signIn: () => `/auth/signin`,
  signUp: () => `/auth/signup`,
  signOut: () => `/auth/signout`,
  resetPassword: () => `/auth/passwordReset`,
  about: () => `/about`,
  guide: () => `/guide`,
  blog: () => `/blog`,
  wizard: () => `/wizard`,
  portal: () => `/portal`,
  proceedings: () => `/portal/proceedings`,
  emailVerification: () => `/auth/email-verification`,
  confirmEmail: () => `/auth/confirm-email`,
}
